services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppVerk\GoogleCloudStorageMediaBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    AppVerk\GoogleCloudStorageMediaBundle\Namer\Strategy\CurrentDateStrategy:
        arguments:
            - '%google_cloud_storage_media.date_strategy_format%'

    AppVerk\GoogleCloudStorageMediaBundle\Flysystem\Retriever\LocalObjectUrlRetriever: ~

    AppVerk\GoogleCloudStorageMediaBundle\Flysystem\Retriever\GoogleObjectUrlRetriever:
        arguments: ['%google_cloud_storage_media.gcs.project_id%', '%google_cloud_storage_media.gcs.bucket_id%', '%google_cloud_storage_media.gcs.key_file_path%']

    AppVerk\GoogleCloudStorageMediaBundle\Namer\Strategy\AbstractNamingStrategy: '@AppVerk\GoogleCloudStorageMediaBundle\Namer\Strategy\CurrentDateStrategy'

    AppVerk\GoogleCloudStorageMediaBundle\Namer\DefaultNamer:
        arguments:
            - '@AppVerk\GoogleCloudStorageMediaBundle\Namer\Strategy\CurrentDateStrategy'

    AppVerk\GoogleCloudStorageMediaBundle\Namer\InvoiceNamer:
        arguments:
            - '@AppVerk\GoogleCloudStorageMediaBundle\Namer\Strategy\CurrentDateStrategy'
            
    AppVerk\GoogleCloudStorageMediaBundle\Doctrine\MediaManager:
        arguments:
            $className: '%google_cloud_storage_media.entities.media_class%'

    AppVerk\GoogleCloudStorageMediaBundle\Service\MediaValidation:
        arguments: ['%google_cloud_storage_media.max_file_size%', '%google_cloud_storage_media.allowed_mime_types%', '%google_cloud_storage_media.groups%']

    AppVerk\GoogleCloudStorageMediaBundle\Service\Storage:
        arguments: ['%google_cloud_storage_media.gcs.project_id%', '%google_cloud_storage_media.gcs.bucket_id%', '%google_cloud_storage_media.gcs.key_file_path%']

    AppVerk\GoogleCloudStorageMediaBundle\Service\v2\StorageService:
        autowire: false

    AppVerk\GoogleCloudStorageMediaBundle\Doctrine\MediaManagerInterface: '@AppVerk\GoogleCloudStorageMediaBundle\Doctrine\MediaManager'

    AppVerk\GoogleCloudStorageMediaBundle\Form\DataTransformer\MediaTransformer:
        arguments:
            $className: '%google_cloud_storage_media.entities.media_class%'
